version: '3.9'
services:
  opentrashmail:
    build:
      context: .
      target: prod

    image: 'abyssox/opentrashmail:latest'
    volumes:
      - './data:/var/www/opentrashmail/data'
      - './logs:/var/www/opentrashmail/logs'
    environment:
      - PUID=1000
      - PGID=1000
      - URL=http://localhost:8080
      - DOMAINS=example.com
      - DATEFORMAT=DD.MM.YYYY HH:mm
      - SKIP_FILEPERMISSIONS=true
      - DISCARD_UNKNOWN=false
      - ADMIN_ENABLED=false
      # - ADMIN_PASSWORD=123456
      # - PASSWORD=123456
      # - ALLOWED_IPS=192.168.0.0/16,2a02:ab:cd:ef::/60
      # - ATTACHMENTS_MAX_SIZE=10000000
      # - MAILPORT_TLS=465
      # - TLS_CERTIFICATE=cert.pem
      # - TLS_PRIVATE_KEY=key.pem
      # - WEBHOOK_URL=https://example.com/webhook

    ports:
      - '2525:25'
      - '8080:80'
